name: lidar_for_fuel
channels:
  - conda-forge
dependencies:
  - python=3.12.*
  - numpy>=1.20.0
  - geopandas
  - conda-forge:pdal>=2.9.*
  - conda-forge:python-pdal>=3.4
# --------- hydra configs --------- #
  - hydra-core
  - hydra-colorlog
# --------- dev dep --------- #
  - pre-commit # hooks for applying linters on commit
  - black # code formatting
  - isort # import sorting
  - flake8 # code analysis
  - pytest
  - pip
  - pip:
    # Install laspy with laszip laz compression (as laszip is an implementation of the laz 1.4 standard)
    - laspy[lazrs]  # Installed via pip because laszip is not handled by the conda package.