# @package _global_

# path to original working directory
# hydra hijacks working directory by changing it to the current log directory,
# so it's useful to have this path as a special variable
# learn more here: https://hydra.cc/docs/next/tutorials/basic/running_your_app/working_directory
work_dir: ${hydra:runtime.cwd}

io:
  input_filename: null
  input_dir: null
  output_dir: null
  # Spatial reference to use to override the one from input las.
  spatial_reference: EPSG:2154

pretreatment: 
  filter:
    dimension: Classification
    keep_values: [1, 2, 3, 4, 5, 9, 66]   # Classes to keep 
  filter_deviation:
    deviation_day: 14
  filter_normalize:
    height: 60

hydra:
  output_subdir: null
  run:
    dir: .